

lwIP_Apps_PATH := modules/lpc4337_m4/lwIP_Apps

lwIP_Apps_SRC_FILES += $(wildcard $(lwIP_Apps_PATH)/src/*.c)
lwIP_Apps_SRC_FILES += $(wildcard $(lwIP_Apps_PATH)/apps/httpserver_raw/src/*.c)
lwip_new_SRC_FILES += $(wildcard $(lwIP_Apps_PATH)/apps/BasicSocketCommandServer/*.c)


lwIP_Apps_INC_FOLDERS += $(lwIP_Apps_PATH)/inc \
			$(lwIP_Apps_PATH)/apps/httpserver_raw/inc

lwIP_Apps_SRC_FOLDERS += $(lwIP_Apps_PATH)/src/       \
               $(lwIP_Apps_PATH)/apps/httpserver_raw/src/      \
               $(lwIP_Apps_PATH)/apps/BasicSocketCommandServer/

